### ISSUE TITLE
WebSocket closes

### ISSUE THREAD

**Issue by sqs** [sourcegraph/lang-typescript#21]
On https://github.com/sourcegraph/sourcegraph/pull/1068/files with the latest browser extension installed in Chrome, with `sourcegraph/lang-typescript` enabled, I see only a loading indicator in the hover. The background page shows the following. The WebSocket close (the yellow-background log entry) occurred while the codeintellify hover showed loading.

![screenshot from 2018-11-19 16-02-47](https://user-images.githubusercontent.com/1976/48742659-af56c300-ec14-11e8-9ecd-314ca113a5aa.png)

(The screenshot shows a portion of my access token, but not enough to be dangerous. Still, I revoked it before posting this. Just mentioning this in case anyone wonders.)

**Comment by felixfbecker** [comment]
I have no idea why these connection losses are happening, or how often they happen, or if it's only Chrome or also Firefox, but I've seen them too.

One way to prevent this would be giving the client a unique session ID and having the client reconnect with the same ID on a connection loss. But that would introduce complexity on the server which would have to keep connections warm and time them out after a while, and it would not be plain LSP.
