### ISSUE TITLE
npm notice created a lockfile as package-lock.json

### ISSUE THREAD

**Issue by sqs** [sourcegraph/lang-typescript#23]
(Low priority)

When I perform a hover at https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/src/vs/vscode.d.ts, in the browser devtools I see the following error log:

```
TypeScript backend [langserver] [tsserver] npm notice created a lockfile as package-lock.json. You should commit this file.
```

There are no direct negative consequences of this, I am just mentioning it. It might cause other users to get confused or to think that this is causing some other problem (which it isn't, but it'd make diagnosing the problem harder). You could either make it not an error (just a `console.log`) or run npm/yarn in such a way that it doesn't create the lockfile.

(The deeper cause of this issue is that the repo uses yarn, not npm.)

![screenshot from 2018-11-20 19-53-32](https://user-images.githubusercontent.com/1976/48818030-f8cf0d00-ecfd-11e8-97c7-5422951dd96f.png)

**Comment by felixfbecker** [comment]
Closing as not worth fixing upstream
