### ISSUE TITLE
External dependency go to def not working for rxjs

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/lang-typescript#70]
Hovering on symbol, then clicking on go to def hangs the panel indefinitely.

Using Chris' `server-url` branch.

For file http://localhost:7080/github.com/sourcegraph/sourcegraph@9bc30656d4ea812647711467c4e6ef742f40793b/-/blob/shared/src/api/protocol/jsonrpc2/connection.ts#L7

![screenflow](https://user-images.githubusercontent.com/133014/51008873-7fd08280-1502-11e9-9f4f-6a9131bb44b3.gif)

**Comment by felixfbecker** [comment]
This is expected, rxjs does not use `declarationMaps` yet (see note in test plan)
